fix docker config for frontend client + add new entries in makefile to prune

diff --git a/frontend/client/Dockerfile.frontend-client.local b/frontend/client/Dockerfile.frontend-client.local
--- a/frontend/client/Dockerfile.frontend-client.local
+++ b/frontend/client/Dockerfile.frontend-client.local
@@ -1,10 +1,11 @@
-FROM node:lts-alpine
+FROM node:lts-alpine AS dev
 
 WORKDIR /frontend
 
-# install project dependencies
-COPY package.json ./
-COPY . ./
-RUN yarn
+# Install dependencies
+COPY package.json yarn.lock* ./
+RUN \
+  [ -f yarn.lock ] && yarn || \
+  (echo "Lockfile not found." && exit 1)
 
 EXPOSE ${PORT}
